mqtt:
  session_expiry: 1h
log:
  level: debug
  format: json
  filename: log.log
persistence:
  session:
    type: memory
  queue:
    type: memory
trace:
  name: lighthouse
  endpoint: http://localhost:14268/api/traces
  sampler: 1.0
  batcher: jaeger